# Generated by Django 4.2 on 2023-06-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sea_map',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
