# Generated by Django 4.2 on 2023-06-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_sea_map_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sea_map',
            options={'verbose_name': 'SEA_MAP', 'verbose_name_plural': 'SEA_MAPs'},
        ),
    ]
