# Generated by Django 4.2 on 2023-06-03 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEA_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=75)),
                ('author', models.CharField(max_length=50)),
                ('publishing_house', models.CharField(max_length=100)),
                ('ISBN', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999), django.core.validators.MinValueValidator(0)])),
                ('Abstract', models.TextField()),
            ],
            options={
                'verbose_name': 'SEA_BOOK',
                'verbose_name_plural': 'SEA_BOOKs',
            },
        ),
    ]
