# Generated by Django 4.2.1 on 2023-06-04 03:46

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_sea_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEA_Booksss',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=75)),
                ('author', models.CharField(max_length=50)),
                ('publishing_house', models.CharField(max_length=100)),
                ('ISBN', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999), django.core.validators.MinValueValidator(0)])),
                ('Abstract', models.TextField()),
            ],
            options={
                'verbose_name': 'SEA_BOOK!',
                'verbose_name_plural': 'SEA_BOOKsss',
            },
        ),
        migrations.AlterField(
            model_name='sea_book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
